# Generated by Django 5.2.1 on 2025-05-24 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'subscription_plan',
                'verbose_name_plural': 'subscription_plans',
                'db_table': 'tb_subscription_plan',
            },
        ),
    ]
