# Generated by Django 5.2.1 on 2025-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_name',
            field=models.CharField(choices=[('info', 'JOTA Info'), ('pro', 'JOTA Pro')], default='info', max_length=150, verbose_name='Plano de assinatura'),
        ),
    ]
