# Generated by Django 5.2.1 on 2025-05-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscriptionplan_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reader',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Leitor do jornal'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Editor de jornal'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscriptionplan'),
        ),
    ]
