# Generated by Django 5.2.1 on 2025-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.AddField(
            model_name='user',
            name='plan_name',
            field=models.CharField(choices=[('info', 'JOTA Info'), ('pro', 'JOTA Pro')], default='info', max_length=150, verbose_name='Plano de assinatura'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
