# Generated by Django 5.2.1 on 2025-05-23 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('post_image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='rascunho', max_length=10, verbose_name='Status')),
                ('scheduled_post', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'tb_news',
            },
        ),
    ]
