# Generated by Django 5.2.1 on 2025-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('authority', 'Poder'), ('taxes', 'Tributos'), ('health', 'Saúde'), ('energy', 'Energia'), ('labor', 'Trabalhista')], max_length=100, null=True),
        ),
    ]
