# Generated by Django 5.2.1 on 2025-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='plan',
            field=models.CharField(choices=[('info', 'JOTA Info'), ('pro', 'JOTA Pro')], default='info', max_length=150, verbose_name='Plano de assinatura'),
        ),
    ]
